# -*- coding: utf-8 -*-
"""Genere le texte T3D de la chaine ShowInventoryWindow, a coller dans le graphe.

La grammaire est reprise telle quelle d'un export reel du Dev Kit : c'est la
seule facon d'etre sur des noms de broches et des champs obligatoires.
"""
import io
import itertools

STRUCT = "/Script/CoreUObject.UserDefinedStruct'/AsaQoLUI/AsaQoLWindowRow.AsaQoLWindowRow'"
WIDGET_CLASS = "/Script/UMG.WidgetBlueprintGeneratedClass'/AsaQoLUI/WBP_AsaQoLTest.WBP_AsaQoLTest_C'"
CLASS_OF = lambda path: "/Script/CoreUObject.Class'" + path + "'"

# Noms mangles des champs de la structure, releves dans l'export : le Break les
# exige a l'identique, le nom lisible ne suffit pas
FIELDS = [
    ("Tab", "Tab_2_2948453E4626A516E4DFAFBC0642D50D", "string"),
    ("Group", "Group_4_4B4E55944EED6E580EA4ACA62DA00658", "string"),
    ("Name", "Name_6_8EC5F9194B8DC2790D1CCFB0F28C99EF", "string"),
    ("Quantity", "Quantity_9_E4AD425D4A0B14E90E444C836008B5CC", "int"),
    ("Lat", "Lat_12_CD7E93504C69A5B5CB3D9A89C0F4E8BF", "real"),
    ("Lon", "Lon_14_152ECAC44D38AB33D6681A8B5B682468", "real"),
    ("Detail", "Detail_18_76751EBC420D88B688C930B33BA9E285", "string"),
]
MANGLED = {plain: mangled for plain, mangled, _ in FIELDS}

_ids = itertools.count(1)


def guid():
    """32 hexadecimaux, uniques dans le collage ; le prefixe rend l'origine lisible"""
    return "A5A0C0DE{:024X}".format(next(_ids))


class Node:
    def __init__(self, name, cls, x, y, extra=None):
        self.name, self.cls, self.x, self.y = name, cls, x, y
        self.extra = list(extra or [])
        self.pins = []
        self.by_name = {}

    def pin(self, name, category, direction=None, sub=None, container=None,
            default=None, default_object=None, default_text=None, friendly=None,
            hidden=False, advanced=False, is_ref=False, is_const=False, autogen=None,
            dv_ignored=False):
        p = dict(id=guid(), name=name, category=category, direction=direction, sub=sub,
                 container=container, default=default, default_object=default_object,
                 default_text=default_text, friendly=friendly, hidden=hidden,
                 advanced=advanced, is_ref=is_ref, is_const=is_const, autogen=autogen,
                 dv_ignored=dv_ignored, links=[])
        self.pins.append(p)
        self.by_name[name] = p
        return p


def link(a, pin_a, b, pin_b):
    """Une liaison s'ecrit des deux cotes : Unreal ne la deduit pas d'un seul"""
    pa, pb = a.by_name[pin_a], b.by_name[pin_b]
    pa["links"].append((b.name, pb["id"]))
    pb["links"].append((a.name, pa["id"]))


TARGET_FRIENDLY = 'NSLOCTEXT("K2Node", "Target", "Target")'


def render_pin(p):
    bits = ["PinId=" + p["id"], 'PinName="{}"'.format(p["name"])]
    if p["friendly"]:
        bits.append("PinFriendlyName=" + p["friendly"])
    if p["direction"]:
        bits.append('Direction="{}"'.format(p["direction"]))
    bits.append('PinType.PinCategory="{}"'.format(p["category"]))
    bits.append('PinType.PinSubCategory=""')
    bits.append("PinType.PinSubCategoryObject=" +
                ('"{}"'.format(p["sub"]) if p["sub"] else "None"))
    bits.append("PinType.PinSubCategoryMemberReference=()")
    bits.append("PinType.PinValueType=()")
    bits.append("PinType.ContainerType=" + (p["container"] or "None"))
    bits.append("PinType.bIsReference=" + str(p["is_ref"]))
    bits.append("PinType.bIsConst=" + str(p["is_const"]))
    bits.append("PinType.bIsWeakPointer=False")
    bits.append("PinType.bIsUObjectWrapper=False")
    bits.append("PinType.bSerializeAsSinglePrecisionFloat=False")
    if p["default"] is not None:
        bits.append('DefaultValue="{}"'.format(p["default"]))
    if p["autogen"] is not None:
        bits.append('AutogeneratedDefaultValue="{}"'.format(p["autogen"]))
    if p["default_object"]:
        bits.append('DefaultObject="{}"'.format(p["default_object"]))
    if p["default_text"]:
        bits.append("DefaultTextValue=" + p["default_text"])
    if p["links"]:
        bits.append("LinkedTo=({})".format(
            "".join("{} {},".format(n, i) for n, i in p["links"])))
    bits.append("PersistentGuid=00000000000000000000000000000000")
    bits.append("bHidden=" + str(p["hidden"]))
    bits.append("bNotConnectable=False")
    bits.append("bDefaultValueIsReadOnly=False")
    bits.append("bDefaultValueIsIgnored=" + str(p["dv_ignored"]))
    bits.append("bAdvancedView=" + str(p["advanced"]))
    bits.append("bOrphanedPin=False")
    return "   CustomProperties Pin ({},)".format(",".join(bits))


def render(node):
    out = ['Begin Object Class={} Name="{}"'.format(node.cls, node.name)]
    out += ["   " + line for line in node.extra]
    out += ["   NodePosX={}".format(node.x),
            "   NodePosY={}".format(node.y),
            "   NodeGuid=" + guid()]
    out += [render_pin(p) for p in node.pins]
    out.append("End Object")
    return "\n".join(out)


BP = "/Script/BlueprintGraph."
Y = 2600


def call(name, owner, member, x, y, extra=None):
    reference = 'FunctionReference=(MemberParent="{}",MemberName="{}")'.format(
        CLASS_OF(owner), member)
    return Node(name, BP + "K2Node_CallFunction", x, y, [reference] + list(extra or []))


# --- L'evenement ----------------------------------------------------------
event = Node("K2Node_CustomEvent_90", BP + "K2Node_CustomEvent", 400, Y, [
    'CustomFunctionName="ShowInventoryWindow"',
    # 0x0D0200C0 : Net | NetReliable | Public | NetClient | BlueprintCallable | BlueprintEvent
    "FunctionFlags=218235072",
])
event.pin("OutputDelegate", "delegate", "EGPD_Output")
event.pin("then", "exec", "EGPD_Output")
event.pin("Title", "string", "EGPD_Output")
event.pin("Rows", "struct", "EGPD_Output", sub=STRUCT, container="Array")
# Les entrees de l'evenement se declarent en plus des broches : sans ces lignes,
# le noeud se recree sans parametre
event.extra += [
    'CustomProperties UserDefinedPin (PinName="Title",PinType=(PinCategory="string"),DesiredPinDirection=EGPD_Output)',
    'CustomProperties UserDefinedPin (PinName="Rows",PinType=(PinCategory="struct",PinSubCategoryObject="{}",ContainerType=Array),DesiredPinDirection=EGPD_Output)'.format(STRUCT),
]

# --- Widget ---------------------------------------------------------------
widget = Node("K2Node_CreateWidget_90", "/Script/UMGEditor.K2Node_CreateWidget", 1000, Y)
widget.pin("execute", "exec")
widget.pin("then", "exec", "EGPD_Output")
widget.pin("Class", "class", sub=CLASS_OF("/Script/UMG.UserWidget"),
           default_object="/AsaQoLUI/WBP_AsaQoLTest.WBP_AsaQoLTest_C")
widget.pin("ReturnValue", "object", "EGPD_Output", sub=WIDGET_CLASS)
widget.pin("OwningPlayer", "object", sub=CLASS_OF("/Script/Engine.PlayerController"))

viewport = call("K2Node_CallFunction_90", "/Script/UMG.UserWidget", "AddToViewport",
                1500, Y, ["AdvancedPinDisplay=Shown"])
viewport.pin("execute", "exec")
viewport.pin("then", "exec", "EGPD_Output")
viewport.pin("self", "object", sub=CLASS_OF("/Script/UMG.UserWidget"), friendly=TARGET_FRIENDLY)
viewport.pin("ZOrder", "int", default="0", autogen="0", advanced=True)

ligne = Node("K2Node_VariableGet_90", BP + "K2Node_VariableGet", 1500, Y + 420, [
    'VariableReference=(MemberParent="{}",MemberName="Ligne")'.format(WIDGET_CLASS),
    "SelfContextInfo=NotSelfContext",
])
ligne.pin("Ligne", "object", "EGPD_Output", sub=CLASS_OF("/Script/UMG.TextBlock"))
ligne.pin("self", "object", sub=WIDGET_CLASS, friendly=TARGET_FRIENDLY)

settext = call("K2Node_CallFunction_91", "/Script/UMG.TextBlock", "SetText", 1950, Y + 420)
settext.pin("execute", "exec")
settext.pin("then", "exec", "EGPD_Output")
settext.pin("self", "object", sub=CLASS_OF("/Script/UMG.TextBlock"), friendly=TARGET_FRIENDLY)
settext.pin("InText", "text")

console = call("K2Node_CallFunction_92", "/Script/Engine.KismetSystemLibrary",
               "ExecuteConsoleCommand", 2400, Y + 420)
console.pin("execute", "exec")
console.pin("then", "exec", "EGPD_Output")
console.pin("self", "object", sub=CLASS_OF("/Script/Engine.KismetSystemLibrary"),
            friendly=TARGET_FRIENDLY,
            default_object="/Script/Engine.Default__KismetSystemLibrary", hidden=True)
console.pin("WorldContextObject", "object", sub=CLASS_OF("/Script/CoreUObject.Object"), is_const=True)
console.pin("Command", "string", default="stat fps")
console.pin("SpecificPlayer", "object", sub=CLASS_OF("/Script/Engine.PlayerController"),
            autogen="None")


# --- Acces au tableau -----------------------------------------------------
# Les deux noeuds ci-dessous ne sont PAS des K2Node_CallFunction ordinaires, et
# c'est ce qui avait fait echouer la premiere version : « Length » est un
# K2Node_CallArrayFunction, et « Get (a copy) » un K2Node_GetArrayItem, qui n'est
# pas un appel de fonction du tout. `KismetArrayLibrary::Array_Get` existe mais
# est marquee BlueprintInternalUseOnly : un collage qui l'invoque est rejete sans
# message. Grammaire relevee sur un export reel.
length = Node("K2Node_CallArrayFunction_90", BP + "K2Node_CallArrayFunction", 900, Y + 900, [
    "bDefaultsToPureFunc=True",
    'FunctionReference=(MemberParent="{}",MemberName="Array_Length")'.format(
        CLASS_OF("/Script/Engine.KismetArrayLibrary")),
])
length.pin("self", "object", sub=CLASS_OF("/Script/Engine.KismetArrayLibrary"),
           friendly=TARGET_FRIENDLY,
           default_object="/Script/Engine.Default__KismetArrayLibrary", hidden=True)
length.pin("TargetArray", "struct", sub=STRUCT, container="Array",
           is_ref=True, is_const=True, dv_ignored=True)
length.pin("ReturnValue", "int", "EGPD_Output", default="0", autogen="0")

gets, breaks = [], []
for slot, index in enumerate((0, 2)):
    getter = Node("K2Node_GetArrayItem_9{}".format(slot), BP + "K2Node_GetArrayItem",
                  900, Y + 1080 + slot * 460, ["bReturnByRefDesired=False"])
    getter.pin("Array", "struct", sub=STRUCT, container="Array")
    getter.pin("Dimension 1", "int", default=str(index), autogen="0")
    getter.pin("Output", "struct", "EGPD_Output", sub=STRUCT)
    gets.append(getter)

    shown = ['ShowPinForProperties({})=(PropertyName="{}",PropertyFriendlyName="{}",bShowPin=True,bCanToggleVisibility=True)'.format(i, mangled, plain)
             for i, (plain, mangled, _) in enumerate(FIELDS)]
    breaker = Node("K2Node_BreakStruct_9{}".format(slot), BP + "K2Node_BreakStruct",
                   1350, Y + 1080 + slot * 460,
                   ["bMadeAfterOverridePinRemoval=True"] + shown +
                   ['StructType="{}"'.format(STRUCT), "AdvancedPinDisplay=Shown"])
    breaker.pin("AsaQoLWindowRow", "struct", sub=STRUCT)
    for _, mangled, category in FIELDS:
        breaker.pin(mangled, category, "EGPD_Output")
    breaks.append(breaker)

# --- Format ---------------------------------------------------------------
FORMAT = "{title} | {count} lignes | {n1} {q1} | {n3} {q3}"
fmt = Node("K2Node_FormatText_90", BP + "K2Node_FormatText", 1800, Y + 900,
           ['PinNames({})="{}"'.format(i, n)
            for i, n in enumerate(("title", "count", "n1", "q1", "n3", "q3"))])
fmt.pin("Format", "text", default_text='NSLOCTEXT("[A5A0C0DE9F35579C14B6B3237F6C0528]", "A5A0C0DE4B3D48390F9714B2A271FA08", "{}")'.format(FORMAT))
fmt.pin("Result", "text", "EGPD_Output")
fmt.pin("title", "string")
fmt.pin("count", "int")
fmt.pin("n1", "string")
fmt.pin("q1", "int")
fmt.pin("n3", "string")
fmt.pin("q3", "int")

# --- Liaisons -------------------------------------------------------------
link(event, "then", widget, "execute")
link(widget, "then", viewport, "execute")
link(widget, "ReturnValue", viewport, "self")
link(widget, "ReturnValue", ligne, "self")
link(ligne, "Ligne", settext, "self")
link(viewport, "then", settext, "execute")
link(settext, "then", console, "execute")
link(fmt, "Result", settext, "InText")
link(event, "Title", fmt, "title")
link(event, "Rows", length, "TargetArray")
link(length, "ReturnValue", fmt, "count")

for slot, (getter, breaker) in enumerate(zip(gets, breaks)):
    suffix = "1" if slot == 0 else "3"
    link(event, "Rows", getter, "Array")
    link(getter, "Output", breaker, "AsaQoLWindowRow")
    link(breaker, MANGLED["Name"], fmt, "n" + suffix)
    link(breaker, MANGLED["Quantity"], fmt, "q" + suffix)

nodes = [event, widget, viewport, ligne, settext, console, length, fmt] + gets + breaks
text = "\n".join(render(n) for n in nodes) + "\n"

OUT = r"C:\Users\Sylvain\AppData\Local\Temp\claude\E--Claude\dc2d8434-cd17-46c2-aacd-064eaa52a51e\scratchpad\showwindow.t3d"
io.open(OUT, "w", encoding="utf-8", newline="\n").write(text)
print("ecrit  :", OUT)
print("noeuds :", len(nodes))
print("taille :", len(text), "caracteres")
